spring:
    datasource:
        url: jdbc:postgressql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USER}
        password: ${PROD_DB_PASSWORD}
        name: easy-job

    sql:
        init:
            mode: always